variables:
  IMAGE_ORG: pubsweet
  IMAGE_NAME: starter
  BASE_DOMAIN: gateway.ps.semioticsquares.com
  CONFIGURATION_REPOSITORY: https://gitlab.coko.foundation/pubsweet/deployment-config.git

stages:
  - build
  - test
  - review
  - staging
  - demo

build:
  image: docker:stable
  stage: build
  script:
    - docker version
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Ignore warning! Cannot perform an interactive login from a non TTY device"
    - docker build -t $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

test:chrome:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
    # setup data for postgres image
    POSTGRES_USER: test
    POSTGRES_PASSWORD: pw
    # connection details for tests
    PGUSER: test
    PGPASSWORD: pw
    NODE_ENV: test
  services:
    - postgres
  script:
    - cd ${HOME}
    # specify host here else it confuses the linked postgres image
    - PGHOST=postgres npx testcafe 'chrome:headless --no-sandbox' test/**/*.test.js

test:firefox:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
    # setup data for postgres image
    POSTGRES_USER: test
    POSTGRES_PASSWORD: pw
    # connection details for tests
    PGUSER: test
    PGPASSWORD: pw
    NODE_ENV: test
  services:
    - postgres
  script:
    - cd ${HOME}
    # specify host here else it confuses the linked postgres image
    - PGHOST=postgres npx testcafe firefox:headless test/**/*.test.js

lint:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run lint

review:
  image: pubsweet/deployer:latest
  stage: review
  variables:
    PACKAGE_NAME: starter
    FORCE_FRESH_DB: "yes"
    REQUIRES_PROVISIONING: "yes"
  environment:
    name: $PACKAGE_NAME/review/$CI_COMMIT_REF_NAME
    # !! kube-lego will fail if domain > 63 chars
    url: "http://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}"
    on_stop: stop_review
  except:
  - master
  script:
    - source deploy.sh
    - create_deployment

stop_review:
  image: pubsweet/deployer:latest
  stage: review
  variables:
    PACKAGE_NAME: starter 
    REQUIRES_PROVISIONING: "yes"
    GIT_STRATEGY: none
  environment:
    name: $PACKAGE_NAME/review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  except:
  - master
  script:
    - source deploy.sh
    - delete_deployment
    - delete_objects_in_environment pvc

staging:
  image: pubsweet/deployer:latest
  stage: staging
  variables:
    PACKAGE_NAME: starter
  environment:
    name: $PACKAGE_NAME/staging
    url: "https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}"
  only:
  - master
  script:
    - source deploy.sh
    - create_deployment

demo:
  image: pubsweet/deployer:latest
  stage: demo
  variables:
    PACKAGE_NAME: starter
  environment:
    name: $PACKAGE_NAME/demo
    url: "https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}"
  when: manual
  script:
    - source deploy.sh
    - create_deployment
