version: '2.1'
services:

  web:
    image: pubsweet/pubsweet:base
    command: sh -c "yarn && yarn server"
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PGHOST: db
      PGUSER: $USER

  db:
    image: postgres:10
    ports:
      - 9432:5432
    environment:
      POSTGRES_USER: $USER
    volumes:
      - ./scripts/test.sql:/docker-entrypoint-initdb.d/test.sql
